### ISSUE TITLE
在微信小程序中使用axios-miniprogram在测试环境访问后台服务器没有问题，但是一发布到生产环境就有问题。

### ISSUE THREAD

**Issue by scottfly189** [zjxxxxxxxxx/axios-miniprogram#61]
### 描述错误

在微信小程序中使用axios-miniprogram在测试环境访问后台服务器没有问题，但是一发布到生产环境就有问题:
访问网络故障：login-error: <Error: request fail>
Error: request fail
    at u (https://usr/appservice.app.js:929:15456)
    at l (https://usr/appservice.app.js:929:15417)
    at fail (https://usr/appservice.app.js:929:20125)
    at Object.fail (https://lib/WASubContext.js:1:123373)
    at Object.fail (https://lib/WASubContext.js:1:123646)
    at I.forEach.v.<computed> (https://lib/WAServiceMainContext.js:1:954786)
    at p (https://lib/WAServiceMainContext.js:1:151650)
    at https://lib/WAServiceMainContext.js:1:152093
    at Vc (https://lib/WAServiceMainContext.js:1:656450)
    at Function.<anonymous> (https://lib/WAServiceMainContext.js:1:735425)
    
    
    >>是axios-miniprogram不是封装的是wx.request,所以请求的时候会有跨域问题？

### 使用过的包管理器

npm

### 验证

- [X] 遵守我们的[行为准则 ](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读[贡献指南](https://github.com/zjxxxxxxxxx/axios-miniprogram/blob/main/CONTRIBUTING.md).
- [X] 阅读[文档](https://axios-miniprogram.com).
- [X] 检查是否还没有报告相同错误的[问题](https://github.com/zjxxxxxxxxx/axios-miniprogram/issues)以避免创建重复。
- [X] 确保这是 axios-miniprogram 问题而不是特定于框架的问题。

**Comment by zjxxxxxxxxx** [comment]
跨域的问题？有没有更详细的异常信息？比如请求的状态码和错误信息。

**Comment by scottfly189** [comment]
谢谢大佬，不是这个问题，axios-miniprogram用在微信原生小程序没有问题。
我最主要是服务端nginx的https没有设置好。
问题解决了！
